name: server-werkflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 * * * *'

jobs:
  lintest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: "src"
        mypy-options: "--ignore-missing-imports --show-error-codes"
        pylint-options: "--rcfile=.pylintrc"
        isort-options: "-w 100"

  builds:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Run tests
      run: python main.py

  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Run tests
      run: python run_tests.py